import json
import re
import logging
from collections import Counter
from datetime import datetime, timedelta

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from app.db.session import get_db
from app.models.user import User
from app.models.journal_entry import JournalEntry
from app.models.emotion_log import EmotionLog
from app.routers.auth import get_current_user
from app.services.engines.factory import get_llm_engine

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/meditate", tags=["meditate"])


def _extract_json(text: str) -> str:
    text = re.sub(r"```(?:json)?\s*", "", text)
    text = re.sub(r"```", "", text).strip()
    start = text.find("{")
    end = text.rfind("}") + 1
    if start != -1 and end > start:
        return text[start:end]
    return text


def _default_script() -> str:
    return (
        "Find a comfortable position and gently close your eyes. "
        "Take a moment to arrive here — let go of anything you were carrying before this moment. "
        "Notice the weight of your body, the surface beneath you holding you completely. "
        "Begin to notice your breath. Not controlling it, just observing it. "
        "With each inhale, you draw in stillness. With each exhale, you soften a little more. "
        "Let your shoulders drop. Let your jaw unclench. Let your hands open. "
        "You have nowhere to be right now. This breath is enough. "
        "Stay here as long as you need. You are safe. You are here."
    )


def _fallback() -> dict:
    return {
        "suggested_pattern": "box",
        "reason": "Box breathing is a balanced technique that steadies the nervous system and brings you back to center.",
        "guided_script": _default_script(),
    }


@router.get("/suggest")
async def get_meditation_suggestion(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Return a personalized meditation suggestion generated by the LLM."""
    try:
        since = datetime.utcnow() - timedelta(days=30)
        emotion_stmt = (
            select(EmotionLog)
            .where(EmotionLog.user_id == current_user.id)
            .where(EmotionLog.created_at >= since)
            .order_by(desc(EmotionLog.created_at))
            .limit(20)
        )
        emotion_logs = (await db.execute(emotion_stmt)).scalars().all()

        journal_stmt = (
            select(JournalEntry)
            .where(JournalEntry.user_id == current_user.id)
            .order_by(desc(JournalEntry.created_at))
            .limit(5)
        )
        journal_entries = (await db.execute(journal_stmt)).scalars().all()

        if emotion_logs:
            counts = Counter(log.primary_emotion for log in emotion_logs)
            top = counts.most_common(3)
            emotion_context = "Recent emotions: " + ", ".join(
                f"{e} ({c}x)" for e, c in top
            )
        else:
            emotion_context = "No recent emotion data."

        if journal_entries:
            excerpts = []
            for e in journal_entries[:3]:
                text = (e.content or "")[:200]
                excerpts.append(f"[{e.emotion or 'neutral'}] {text}")
            journal_context = "Recent journal excerpts:\n" + "\n---\n".join(excerpts)
        else:
            journal_context = "No recent journal entries."

        system_prompt = "You are Serenity's AI meditation guide. Generate a personalized meditation session as valid JSON only — no markdown, no explanation outside the JSON."

        user_prompt = f"""Analyze this user's emotional data and return ONLY a JSON object:

{emotion_context}
{journal_context}

Return ONLY this JSON (no other text):
{{
  "suggested_pattern": "<one of: box, calm, deep>",
  "reason": "<1-2 sentences explaining why, referencing their specific emotional data>",
  "guided_script": "<a warm, personal 4-5 minute guided meditation script (400-600 words). Address the user as you. Reference their emotional patterns naturally. Include: settling in, body scan, breathing focus, visualization or affirmation, gentle close.>"
}}

Pattern selection rules:
- box (4-4-4-4): anxiety, stress, racing thoughts, overwhelm
- calm (4-7-8): deep tension, insomnia, anger, agitation
- deep (5-5): sadness, low energy, disconnection, grounding needed"""

        engine = get_llm_engine()
        raw = await engine.generate(
            system_prompt,
            [{"role": "user", "content": user_prompt}],
            max_tokens=1200,
            temperature=0.75,
        )

        data = json.loads(_extract_json(raw))

        if data.get("suggested_pattern") not in ("box", "calm", "deep"):
            data["suggested_pattern"] = "box"
        if not data.get("reason"):
            data["reason"] = "A balanced session to help you find calm."
        if not data.get("guided_script"):
            data["guided_script"] = _default_script()

        return data

    except json.JSONDecodeError as e:
        logger.warning(f"Meditation JSON parse failed: {e}")
        return _fallback()
    except Exception as e:
        logger.error(f"Meditation suggest failed: {e}")
        return _fallback()
